sudo: required
services:
  - docker

before_install:
  - docker build -t eggjr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eggjr/docker-react npm run test -- --coverage

before_deploy:
  - pip install --user awscli  # Install AWS CLI if not available
  - export AWS_REGION="ap-southeast-2"  # Manually set AWS region (or replace with your region)
  - echo "Deploying to AWS Region: $AWS_REGION"

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"  # Replace with your actual AWS region if different
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-160885253404"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY  # Corrected variable name
  secret_access_key: $AWS_SECRET_ACCESS_KEY  # Corrected and removed "secure"
