dist: focal
sudo: required
services:
  - docker

before_install:
  - docker build -t eggjr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eggjr/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  #edge: true  # Use latest Travis CI deployment features
  region: "ap-southeast-2"  # Replace with your actual AWS region if different
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-160885253404"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY  # Corrected variable name
  secret_access_key: $AWS_SECRET_KEY  # Corrected and removed "secure"
